// <auto-generated />
using System;
using InternshipNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternshipNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120183001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternshipNet.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Industry = "Technology",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 2,
                            Industry = "Search & AI",
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("InternshipNet.Models.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Internships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Description = "C# and WPF tasks",
                            Title = ".NET Developer Intern"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            Description = "Kotlin and Java",
                            Title = "Android Intern"
                        });
                });

            modelBuilder.Entity("InternshipNet.Models.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Resumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "My Resume Content...",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("InternshipNet.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ihor@test.com",
                            Name = "Ihor Braichenko"
                        });
                });

            modelBuilder.Entity("InternshipNet.Models.StudentApplication", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("InternshipId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "InternshipId");

                    b.HasIndex("InternshipId");

                    b.ToTable("StudentApplications");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            InternshipId = 1,
                            AppliedDate = new DateTime(2025, 11, 20, 18, 30, 1, 615, DateTimeKind.Utc).AddTicks(5218),
                            Status = 0
                        });
                });

            modelBuilder.Entity("InternshipNet.Models.Internship", b =>
                {
                    b.HasOne("InternshipNet.Models.Company", "Company")
                        .WithMany("Internships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InternshipNet.Models.Resume", b =>
                {
                    b.HasOne("InternshipNet.Models.Student", "Student")
                        .WithOne("Resume")
                        .HasForeignKey("InternshipNet.Models.Resume", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipNet.Models.StudentApplication", b =>
                {
                    b.HasOne("InternshipNet.Models.Internship", "Internship")
                        .WithMany("Applications")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipNet.Models.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Internship");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipNet.Models.Company", b =>
                {
                    b.Navigation("Internships");
                });

            modelBuilder.Entity("InternshipNet.Models.Internship", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("InternshipNet.Models.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Resume")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
